name = "NumericalAlgorithms"
uuid = "3b47cccd-2e0f-43d2-aaa1-0b61cbee3591"
authors = ["Murat Koptur <mkoptur3@gmail.com>"]
version = "0.1.5"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.5"
