name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: Version to register or component to bump
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/ccheckout@latest
    - uses: julia-actions/setup-julia@latest
      with:
        version: 1.5.3
    - uses: julia-actions/julia-buildpkg@latest
    - uses: julia-actions/julia-runtest@latest
    - uses: julia-actions/julia-processcoverage@latest
    - uses: codecov/codecov-action@latest
      with:
        file: lcov.info
