name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: Version to register or component to bump
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: julia-actions/setup-julia@v1.6.0
      with:
        version: 1.5.3
    - uses: julia-actions/julia-buildpkg@v1.1.1
    - uses: julia-actions/julia-runtest@v1.5.1
    - uses: julia-actions/julia-processcoverage@v1
    - uses: codecov/codecov-action@v1.2.1
      with:
        file: lcov.info
    - uses: julia-actions/RegisterAction@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: JuliaRegistries/TagBot@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
